# single line comment
"""
Multiline comment...
Hello, it's me!
How are you?...
"""
'''
Multiline comment...
Hello, it's Raman...
How are you?
'''
# Comments help to maintain understanding and readibility